### ISSUE TITLE
can't build examples

### ISSUE THREAD

**Issue by martialgallorini** [elaye/ofxCurlNoise#1]
hello,

i would like to try your addons but i am unable to build the examples. Well, it builds but won't run

here are the errors i get : 

[ error ] ofAppGLFWWindow: 65544: GLX: Failed to create context: BadValue (integer parameter out of range for operation)
[ error ] ofAppGLFWWindow: couldn't create GLFW window
[ error ] ofAppGLFWWindow: 65538: There is no current context

Note : i am using openFrameworks 0.9 Stable under Ubuntu 14.04.3 64 Bits

any clue ?

**Comment by elaye** [comment]
It's probably a problem with your graphic card driver. To run the examples you need to be able to run OpenGL 4.3 in order to use compute shaders.
You can run `glxinfo | grep version` to know which version of OpenGL you can run.

**Comment by martialgallorini** [comment]
Hello,

Thanks for the answer.

Ok so i think i won't be able to use it as i am stuck with Nvidia 340 proprietary drivers. I think this is a limitation on my GPU (NVidia GeForce 320M) which is quite old now.

Is there a reason you are using OpenGL 4.3 ? Which also prevent using it in Mac as no mac can actually use more than OpenGL 3.2 !

thanks a lot

**Comment by elaye** [comment]
OpenGL 4.3 is needed as the addon uses compute shaders. Apparently compute shaders are not supported on Mac yet. 
An alternative would be to use OpenCL. You can check this addon: [ofxMSAOpenCL](https://github.com/memo/ofxMSAOpenCL) which I believe should work on Mac. The idea is the same and it should be relatively easy to translate the compute shader code from the examples to OpenCL code.

**Comment by martialgallorini** [comment]
Ok, thanks for the answer. I will have a look at ofxMSAOpenCL.
I am quite a noob when dealing with OpenGL and don't know the difference between different shaders yet. So i just wanted to know if you were using specific properties in computer shader that you couldn't find in common shaders

**Comment by ghost** [comment]
I had the same problem in a similar Mac A1278, with an Intel graphics card. I think the problem is within the scope of the shader model of my graphics card as mentioned. i confirm i was able in the past to run the memoakten addon, but it needed some automaton, in the sense of lowering the specs of the render (number of particles, resolution, etc.), to be able to get smooth stuff. and of course curl noise looks better. or at least different. i think a nice suggestion would be to port this addon to opencl, and see if we can get it running on older macs, without shader model 4.2
